# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nnmf_rcpp <- function(A, W, H, inner_max_iter) {
    .Call('_NNLM_nnmf_rcpp', PACKAGE = 'NNLM', A, W, H, inner_max_iter)
}

